fix spacing

diff --git a/task-pull-request.yaml b/task-pull-request.yaml
--- a/task-pull-request.yaml
+++ b/task-pull-request.yaml
@@ -1,5 +1,8 @@
 ﻿apiVersion: tekton.dev/v1beta1
 kind: Task
+metadata:
+  labels:
+    app.kubernetes.io/version: '0.1'
   name: pull-request
 spec:
   description: Create a pull request
@@ -46,76 +49,76 @@ spec:
       image: 'quay.io/tosmi/ubi9-utils:latest'
       name: pull-request
       resources: {}
-      script: >
+      script: |
         #!/bin/bash
 
 
-        set -eu -o pipefail
+         set -eu -o pipefail
 
 
-        echo "Verbose           : ${PARAM_VERBOSE}"
+         echo "Verbose           : ${PARAM_VERBOSE}"
 
-        echo "Source branch     : ${PARAM_SOURCE_BRANCH}"
+         echo "Source branch     : ${PARAM_SOURCE_BRANCH}"
 
-        echo "Destination branch: ${PARAM_DESTINATION_BRANCH}"
+         echo "Destination branch: ${PARAM_DESTINATION_BRANCH}"
 
-        echo "Git token         : ${PARAM_GIT_TOKEN}"
+         echo "Git token         : ${PARAM_GIT_TOKEN}"
 
-        echo "Git URL           : ${PARAM_GIT_URL}"
+         echo "Git URL           : ${PARAM_GIT_URL}"
 
-        echo "Git pull URL      : ${PARAM_GIT_PULL_URL}"
-
-
-        if [ "${PARAM_VERBOSE}" = "true" ] ; then
-            set -x
-        fi
+         echo "Git pull URL      : ${PARAM_GIT_PULL_URL}"
 
 
-        RED="\e[31m"
-
-        YELLOW="\e[33m"
-
-        BOLD="\033[1m"
-
-        NC="\e[0m"
+         if [ "${PARAM_VERBOSE}" = "true" ] ; then
+             set -x
+         fi
 
 
-        error() {
-            local MESSAGE="$1"
-            local DATE
+         RED="\e[31m"
 
-            DATE=$(date "+%d/%b/%Y:%H:%M:%S %z")
+         YELLOW="\e[33m"
 
-            # shellcheck disable=SC3037
-            echo -e "[${DATE}] ${RED}ERROR:${NC} $MESSAGE" >&2
-            exit 1
-        }
+         BOLD="\033[1m"
+
+         NC="\e[0m"
 
 
-        info() {
-            local MESSAGE="$1"
-            local DATE
+         error() {
+             local MESSAGE="$1"
+             local DATE
 
-            DATE=$(date "+%d/%b/%Y:%H:%M:%S %z")
+             DATE=$(date "+%d/%b/%Y:%H:%M:%S %z")
 
-            # shellcheck disable=SC3037
-            echo -e "[${DATE}] ${YELLOW}INFO:${NC} $MESSAGE" >&2
+             # shellcheck disable=SC3037
+             echo -e "[${DATE}] ${RED}ERROR:${NC} $MESSAGE" >&2
+             exit 1
+         }
 
-            return 0
-        }
+
+         info() {
+             local MESSAGE="$1"
+             local DATE
+
+             DATE=$(date "+%d/%b/%Y:%H:%M:%S %z")
+
+             # shellcheck disable=SC3037
+             echo -e "[${DATE}] ${YELLOW}INFO:${NC} $MESSAGE" >&2
+
+             return 0
+         }
 
 
-        PATH=/bin:/usr/bin
+         PATH=/bin:/usr/bin
 
-        PARAM_GIT_PULL_URL=$(echo ${PARAM_GIT_PULL_URL} | cut -d "{" -f1 )
+         PARAM_GIT_PULL_URL=$(echo ${PARAM_GIT_PULL_URL} | cut -d "{" -f1 )
 
-        HTTP_STATUS=$(curl -L   -X POST   -H "Accept:
-        application/vnd.github+json"   -H "Authorization: Bearer
-        ${PARAM_GIT_TOKEN} "  -H "X-GitHub-Api-Version: 2022-11-28"  
-        ${PARAM_GIT_PULL_URL}  -d "
-                       {
-                         \"base\": \"${PARAM_DESTINATION_BRANCH}\",
-                         \"head\": \"${PARAM_SOURCE_BRANCH}\",
-                         \"body\": \"We want to merge into ${PARAM_DESTINATION_BRANCH}.\",
-                         \"title\": \"Merge into ${PARAM_DESTINATION_BRANCH}\"
-                       }")
+         HTTP_STATUS=$(curl -L   -X POST   -H "Accept:
+         application/vnd.github+json"   -H "Authorization: Bearer
+         ${PARAM_GIT_TOKEN} "  -H "X-GitHub-Api-Version: 2022-11-28"  
+         ${PARAM_GIT_PULL_URL}  -d "
+                        {
+                          \"base\": \"${PARAM_DESTINATION_BRANCH}\",
+                          \"head\": \"${PARAM_SOURCE_BRANCH}\",
+                          \"body\": \"We want to merge into ${PARAM_DESTINATION_BRANCH}.\",
+                          \"title\": \"Merge into ${PARAM_DESTINATION_BRANCH}\"
+                        }")
